
package GUI;

import Entity.PravdyViery;
import InterfacesMysqlobjectOther.*;
import InterfacesMysqlobjectOther.PravdyVieryDaoFactory;
import java.util.List;
import javax.swing.JOptionPane;


public class PravdyVieryForm extends javax.swing.JDialog {

  private PravdyVieryDao pravdyMySql = PravdyVieryDaoFactory.INSTANCE.getPravdyVieryDao();
  List<PravdyViery> vsetkyPravdy = pravdyMySql.dajVsetky();
    
    
    public PravdyVieryForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        setLocationRelativeTo(null);
        obsahTextArea.setVisible(false);
        nazvyList.setListData(vsetkyPravdy.toArray());
        this.setTitle("Základné pravdy kresťanskej viery");
        
       this.setSize(240, 350);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        nazvyList = new javax.swing.JList();
        odstranitButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        obsahTextArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nazvyList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        nazvyList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nazvyListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(nazvyList);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 13, 144, 278));

        odstranitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Obrazky/bin1.jpg"))); // NOI18N
        odstranitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                odstranitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(odstranitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 237, 61, 54));

        obsahTextArea.setColumns(20);
        obsahTextArea.setRows(5);
        jScrollPane2.setViewportView(obsahTextArea);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 13, 328, 278));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Obrazky/12714007_10153841305320690_888798132_n.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 580, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nazvyListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nazvyListMouseClicked
       if(evt.getClickCount()==2){
          PravdyViery pravda = (PravdyViery) nazvyList.getSelectedValue();
         this.setSize(590, 350);
          obsahTextArea.setVisible(true);
          obsahTextArea.setText(pravda.getObsah());
          
          
       }
    }//GEN-LAST:event_nazvyListMouseClicked

    private void odstranitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_odstranitButtonActionPerformed
        PravdyViery pravda = (PravdyViery) nazvyList.getSelectedValue();
        if(pravda == null){
            JOptionPane.showMessageDialog(this, "Nie je vybraná žiadna položka", "Chyba", JOptionPane.ERROR_MESSAGE);
            return;
        }
        pravdyMySql.odstranit(pravda);
        refresh();
    }//GEN-LAST:event_odstranitButtonActionPerformed

    public void refresh(){
       
        nazvyList.setListData( pravdyMySql.dajVsetky().toArray());
          this.setSize(240, 350);
         obsahTextArea.setVisible(false);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PravdyVieryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PravdyVieryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PravdyVieryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PravdyVieryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PravdyVieryForm dialog = new PravdyVieryForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList nazvyList;
    private javax.swing.JTextArea obsahTextArea;
    private javax.swing.JButton odstranitButton;
    // End of variables declaration//GEN-END:variables
}
