/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Entity.Umysel;
import java.awt.Component;
import java.awt.Frame;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import Entity.UmyselFile;
import InterfacesMysqlobjectOther.MysqlUmysel;

/**
 *
 * @author Šimon
 */
public class pridajUmyselForm extends javax.swing.JDialog {

    
    
    
   
    /**
     * Creates new form pridajUmyselForm
     */
    public pridajUmyselForm(Frame owner, boolean modal) {
        super(owner, true);
         initComponents();
        
    }

    public pridajUmyselForm() {
        initComponents();
        this.setTitle("Pridaj úmysel");
        this.setSize(400, 334);
        Image im = Toolkit.getDefaultToolkit().getImage("a2.jpg");
        this.setIconImage(im);
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        umText = new javax.swing.JTextField();
        pridajButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Chcem sa modliť aj za: ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 40, 230, 30);

        umText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                umTextActionPerformed(evt);
            }
        });
        getContentPane().add(umText);
        umText.setBounds(120, 100, 165, 26);

        pridajButton.setBackground(new java.awt.Color(204, 255, 255));
        pridajButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        pridajButton.setText("Pridať");
        pridajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pridajButtonActionPerformed(evt);
            }
        });
        getContentPane().add(pridajButton);
        pridajButton.setBounds(170, 160, 87, 29);

        jButton1.setBackground(new java.awt.Color(204, 255, 255));
        jButton1.setText("Zatvoriť");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(280, 200, 89, 29);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Šimon\\Desktop\\projekt\\obr\\s1.png")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-40, 0, 430, 280);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void umTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_umTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_umTextActionPerformed

    private void pridajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pridajButtonActionPerformed
   	
        
      MysqlUmysel zoznam = new MysqlUmysel();
      Umysel novy = new Umysel(umText.getText());
		
			if (umText.getText().equals("")) {
				return;
			}
			zoznam.pridat(novy);
			this.setVisible(false);
		
		this.setVisible(false);
    }//GEN-LAST:event_pridajButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pridajUmyselForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pridajUmyselForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pridajUmyselForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pridajUmyselForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pridajUmyselForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton pridajButton;
    private javax.swing.JTextField umText;
    // End of variables declaration//GEN-END:variables
}
